export { default as AnimatedWaves } from './AnimatedWaves';
export { default as FloatingOrbs } from './FloatingOrbs';
export { default as CPISScoreDisplay } from './CPISScoreDisplay';
export { default as UpcomingOneOnOnes } from './UpcomingOneOnOnes';
export { default as StatsGrid } from './StatsGrid';
export { default as CPISDimensionBreakdown } from './CPISDimensionBreakdown';
export { default as LegacyPerformanceBreakdown } from './LegacyPerformanceBreakdown';
export { default as GoalsWithRisk } from './GoalsWithRisk';
export { default as QuickActions } from './QuickActions';
export { default as ManagerGoalCascade } from './ManagerGoalCascade';
export { default as RecentActivity } from './RecentActivity';
export { default as PerformanceTrendChart } from './PerformanceTrendChart';
export { default as SkillGapRadar } from './SkillGapRadar';
export { default as PeerComparison } from './PeerComparison';
export { default as LearningProgress } from './LearningProgress';
export { default as RecognitionFeed } from './RecognitionFeed';
export { default as GoalVelocity } from './GoalVelocity';
export { default as MetricTooltip, METRIC_GLOSSARY, getThemeStyles, ensureAnimations } from './MetricTooltip';
export { riskBadge, ratingStars, MANAGER_ROLES } from './dashboardUtils';

export type { CPISScoreDisplayProps } from './CPISScoreDisplay';
export type { StatItem } from './StatsGrid';
export type { ActivityItem } from './RecentActivity';
